url: "stephherbers.github.io"
baseurl: "/Resume"

# Site settings
title: Portfolio of Steph Herbers
email: sherbers489@gmail.com
description: "Portfolio of Steph's work"

markdown: kramdown
remote_theme: y7kim/agency-jekyll-theme
permalink: pretty
